[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "OkadaTorch"
description = "PyTorch implementation of Okada's formula "
readme = "README.md"
dependencies = [
    "torch"
]